services:
      
  rabbit-mq:
    build: 
      context: ./rabbitmq-configs
      dockerfile: Dockerfile
    container_name: notification-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rest-reserve

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - rest-reserve
  
  user-service:
    build: 
     context: ./user-service
     dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - rest-reserve
    depends_on:
      - user-db
      - rabbit-mq

  user-db:
    image: postgres:latest
    container_name: user-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"

  restaurant-service:
    build: 
      context: ./restaurant-service
      dockerfile: Dockerfile
    container_name: restaurant-service
    ports:
      - "8082:8082"
    networks:
      - rest-reserve
    depends_on:
      - restaurant-db
      - rabbit-mq

  restaurant-db:
    image: postgres:latest
    container_name: restaurant-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restaurant-db
    ports:
      - "5433:5432"

  reservation-service:
    build: 
      context: ./reservation-service
      dockerfile: Dockerfile
    container_name: reservation-service
    ports:
      - "8083:8083"
    networks:
      - rest-reserve
    depends_on:
      - reservation-db
      - rabbit-mq

  reservation-db:
    image: postgres:latest
    container_name: reservation-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reservation-db
    ports:
      - "5434:5432"

#   notification-service:
#     build: 
#       context: ./notification-service
#       dockerfile: Dockerfile
#     container_name: notification-service
#     ports:
#       - "8084:8084"
#     networks:
#       - rest-reserve
#     depends_on:
#       - rabbit-mq

volumes:
  rabbitmq_data:

networks:
  rest-reserve:
    driver: "bridge"