services:

  rabbit-mq:
    build: 
      context: ./rabbitmq-configs
      dockerfile: Dockerfile
    container_name: notification-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rest-reserve

  user-db:
    image: postgres:latest
    container_name: user-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"

  restaurant-db:
    image: postgres:latest
    container_name: restaurant-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restaurant-db
    ports:
      - "5433:5432"

  reservation-db:
    image: postgres:latest
    container_name: reservation-db
    networks:
      - rest-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reservation-db
    ports:
      - "5434:5432"

volumes:
  rabbitmq_data:

networks:
  rest-reserve:
    driver: "bridge"