spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


      routes:
        - id: ms-restaurants
          uri: http://restaurant-service:8082
          predicates:
            - Method=POST, GET, PATCH, DELETE
            - Path=/restaurant, /restaurant/{id}

        - id: ms-restaurants
          uri: http://restaurant-service:8082
          predicates:
            - Method=POST, GET, PATCH, DELETE
            - Path=/address, /address/{id}, /address/restaurant/{id}

        - id: ms-restaurants
          uri: http://restaurant-service:8082
          predicates:
            - Method=POST, GET, PATCH, DELETE
            - Path=/review, /review/{id}j, /review/restaurant/{id}

        - id: ms-restaurants
          uri: http://restaurant-service:8082
          predicates:
            - Method=POST, DELETE
            - Path=/menu, /menu/{id}

        - id: ms-users
          uri: http://user-service:8081
          predicates:
            - Method=POST, GET
            - Path=/users, /users/{id}, /login

        - id: ms-reservation
          uri: http://reservation-service:8083
          predicates:
            - Method=POST, GET, PUT
            - Path=/reserves, /reserves/{id}, /reserves/user/{id}, /reserves/restaurant/{id}
